[sessions]

[sessions.lint]
# disable reformatting for now
run_isort = false
include_devel = true

# disable reformatting for now
run_black = false

# Add more configuration settings here to adjust to your collection;
# see https://ansible.readthedocs.io/projects/antsibull-nox/config-file/#basic-linting-sessions

[sessions.docs_check]
# Add configuration settings here to adjust to your collection;
# see https://ansible.readthedocs.io/projects/antsibull-nox/config-file/#collection-documentation-check

[sessions.ansible_test_sanity]
include_devel = true

[sessions.ansible_lint]
include_devel = true
