[sessions]

[sessions.lint]
# disable reformatting for now
run_isort = false
run_pylint = false
run_yamllint = false
run_mypy = false
run_antsibullnox_config_lint
include_devel = true

# disable reformatting for now
run_black = false

# Add more configuration settings here to adjust to your collection;
# see https://ansible.readthedocs.io/projects/antsibull-nox/config-file/#basic-linting-sessions

[sessions.ansible_test_sanity]
include_devel = true

[sessions.ansible_lint]
